services:
  dialektor-backend:
    build: ./dialektor-backend
    environment:
      - FLASK_PORT=3000
      - DATABASE_HOST=dialektor-db
    ports:
      - "3000:3000"
    depends_on:
      - dialektor-db
  dialektor-db:
    build: ./dialektor-backend/db
    ports: 
      - "5432:5432"
